# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(first_name: 'toby', password_digest: 'password')
User.create(first_name: 'natalia', password_digest: 'password')
User.create(first_name: 'teddy', password_digest: 'password')
List.create(name: 'Hiking')
List.create(name: 'Biking')
List.create(name: 'Canoeing')
Category.create(name: 'Pack')
Category.create(name: 'Tent')
Category.create(name: 'Sleeping Bag')
Category.create(name: 'Bear Gear')
Category.create(name: 'Water Filtration')
Category.create(name: 'Cookware')
Category.create(name: 'Bike')
Category.create(name: 'Helmet')
Category.create(name: 'Bike Bag')
Category.create(name: 'Canoe')
Item.create(name: 'Osprey')
Item.create(name: 'Granite Gear')
Item.create(name: 'Deuter')
Item.create(name: 'Exos')
Item.create(name: 'REI')
Item.create(name: 'Big Agnes')
Item.create(name: 'Eureka')
Item.create(name: 'Osprey Tent')
Item.create(name: 'Warm Bag')
Item.create(name: 'Cold Bag')
Item.create(name: 'Pot')

Category.first.items.push(Item.first)
Category.first.items.push(Item.find(2))
Category.first.items.push(Item.find(3))
Category.first.items.push(Item.find(4))
Category.second.items.push(Item.find(5))
Category.second.items.push(Item.find(6))
Category.second.items.push(Item.find(7))
Category.third.items.push(Item.find(9))
Category.third.items.push(Item.find(10))
Category.find(6).items.push(Item.find(11))

List.first.categories.push(Category.first)
List.first.categories.push(Category.find(2))
List.first.categories.push(Category.find(3))
List.first.categories.push(Category.find(4))
List.first.categories.push(Category.find(5))
List.first.categories.push(Category.find(6))
List.second.categories.push(Category.find(2))
List.second.categories.push(Category.find(3))
List.second.categories.push(Category.find(6))
List.second.categories.push(Category.find(7))
List.second.categories.push(Category.find(8))
List.second.categories.push(Category.find(9))
List.last.categories.push(Category.find(10))
List.last.categories.push(Category.find(2))
List.last.categories.push(Category.find(3))
List.last.categories.push(Category.find(5))
List.last.categories.push(Category.find(6))


UserListCategoryItem.create(user_id: 1, list_id: 1, category_id: 1, item_id: 1)
UserListCategoryItem.create(user_id: 1, list_id: 1, category_id: 1, item_id: 2)
