# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create(first_name: 'admin', last_name: 'admin', email: 'admin@example.com', password: 'password', admin: 'true')
User.create(first_name: 'natalia', last_name: 'hess', email: 'natalia@natalia.com', password: 'password', admin: 'false')
User.create(first_name: 'toby', last_name: 'zitsman', email: 'toby@toby.com', password: 'password', admin: 'false')

List.create(name: 'Hiking', image: 'https://scontent-yyz1-1.xx.fbcdn.net/v/t1.0-9/14238234_10207786522205917_3580828806313491037_n.jpg?oh=5f33630edb6b80123caed2741911ad8e&oe=58BFECC8')
# Item.create(name: '', brand: '', weight: , size: , unit: , price: , image: 'https://www.rei.com')
Category.create(name: 'Pack')
Item.create(name: 'Atmos', brand: 'Osprey', weight: 4.2, size: 65, price: 260, unit: 'liters', image: 'https://www.rei.com/media/5e79d337-3acb-4494-86e1-fc455cbf40b4?size=2000%2520')
Item.create(name: "Blaze A.C.", brand: 'Granite Gear', weight: 2.85, size: 60, price: 240, unit: 'liters', image: 'https://www.rei.com//media/c31b67f8-3754-4ed9-b8bb-b39090f2002f')
Item.create(name: 'ACT Lite', brand: 'Deuter', weight: 3.9, size: 60, price: 209, unit: 'liters' , image: 'https://www.rei.com/media/1d9791c0-0064-4ac6-a093-3d2456746a94?size=2000')
Item.create(name: 'Stout', brand: 'Gregory', weight: 3.75, size: 65, price: 200, unit: 'liters', image: 'https://www.rei.com/media/1fa6c11f-fc8e-4892-9f3e-cbae6d03105b')
Item.create(name: 'Zulu', brand: 'Gregory', weight: 3.55, size: 65, price: 230, unit: 'liters', image: 'https://www.rei.com/media/d5abd906-31c0-45cf-a79c-4f5647bce168')
Item.create(name: 'Flash', brand: 'REI', weight: 3.5 , size: 65 , price: 200, unit: 'liters', image: 'https://www.rei.com/media/0bf66b86-fa2a-4bfe-8d5e-ea57dd75679e')
Item.create(name: 'Exos', brand: 'Osprey', weight: 2.5 , size: 58 , unit: 'liters', price: 220 ,image: 'https://www.rei.com//media/065a3d68-aa00-4b90-9ee9-5cf688a4f95b')
Item.create(name: 'Crown VC', brand: 'Granite Gear', weight: 2.1 , size: 60, unit: 'liters', price: 200,image: 'https://www.rei.com//media/e56a7a29-c729-43b2-9242-e738228de0e0')
Item.create(name: 'Croz', brand: 'Vaude', weight: 3, size: 48, unit: 'liters', price: 180, image: 'https://images-na.ssl-images-amazon.com/images/I/41KQEeGy3WL._UX342_.jpg')
Category.first.items.push(Item.first)
Category.first.items.push(Item.find(2))
Category.first.items.push(Item.find(3))
Category.first.items.push(Item.find(4))
Category.first.items.push(Item.find(5))
Category.first.items.push(Item.find(6))
Category.first.items.push(Item.find(7))
Category.first.items.push(Item.find(8))
Category.first.items.push(Item.find(9))

Category.create(name: 'Tent')

Item.create(name: 'Laser Ultra', brand: 'Terra Nova', weight: 1.1, size: 1, unit: 'people', price: 1000, image: 'http://content.backcountry.com/images/items/900/TNV/TNV0001/ONECOL.jpg')
Item.create(name: 'Flylite', brand: 'MSR', weight: 1.6, size: 2, unit: 'people', price: 350, image: 'http://content.backcountry.com/images/items/900/CAS/CAS003I/BL.jpg')
Item.create(name: 'Specialist Duo Shelter', brand: 'Sea to Summit', weight: 1.2, size: 1, unit: 'people', price: 500, image: 'http://content.backcountry.com/images/items/900/STS/STS0122/ONECOL.jpg')
Item.create(name: 'Fly Creek HV UL 1', brand: 'Big Agnes', weight: 1.7, size: 1, unit: 'people', price: 350, image: 'http://content.backcountry.com/images/items/1200/BAG/BAG000V/SIL.jpg')
Item.create(name: 'Blaze 1', brand: 'Nemo', weight: 1.75, size: 1, unit: 'people', price: 370, image: 'http://content.backcountry.com/images/items/medium/NEM/NEM004A/ONECOL.jpg')
Item.create(name: 'Carbon Reflex 2', brand: 'MSR', weight: 1.8, size: 2, unit: 'people', price: 500, image: 'http://content.backcountry.com/images/items/900/CAS/CAS007F/RD.jpg')
Item.create(name: 'Fly Creek HV UL 2', brand: 'Big Agnes', weight: 1.9, size: 2, unit: 'people', price: 390, image: 'http://content.backcountry.com/images/items/900/BAG/BAG000W/SIL.jpg')
Item.create(name: 'Blaze 2P', brand: 'Nemo', weight: 2, size: 2, unit: 'people', price: 450, image: 'http://content.backcountry.com/images/items/900/NEM/NEM004B/ONECOL.jpg')
Item.create(name: 'Tensegrity 2 Elite', brand: 'Sierra Designs', weight: 2.2, size: 2, unit: 'people', price: 490, image: 'http://content.backcountry.com/images/items/900/SDS/SDS003O/SIDEYEDETN.jpg')
Item.create(name: 'Copper Spur UL 1', brand: 'Big Agnes', weight: 2.1, size: 1, unit: 'people', price: 380, image: 'http://content.backcountry.com/images/items/900/BAG/BAG001F/TERCOT.jpg')
Item.create(name: 'Quarter Dome 2', brand: 'REI', weight: 3.1, size: 2, unit: 'people', price: 300, image: 'https://www.rei.com/media/bd845230-579e-4871-9e29-096066939066')
Category.second.items.push(Item.find(10))
Category.second.items.push(Item.find(11))
Category.second.items.push(Item.find(12))
Category.second.items.push(Item.find(13))
Category.second.items.push(Item.find(14))
Category.second.items.push(Item.find(15))
Category.second.items.push(Item.find(16))
Category.second.items.push(Item.find(17))
Category.second.items.push(Item.find(18))
Category.second.items.push(Item.find(19))
Category.second.items.push(Item.find(20))

Category.create(name: 'Sleeping Bag')
Item.create(name: 'Flash', brand: 'REI', weight: 1.75, size: 29, unit: "F", price: 180, image: 'https://www.rei.com/media/13cfda70-4b63-42d0-96f2-91a7a920fc6d')
Item.create(name: 'Spark SPI', brand: 'Sea to Summit', weight: 0.85, size: 46, unit: "F", price: 319, image: 'https://www.rei.com/media/d04806c9-a99b-44eb-87b1-d74437ca2809')
Item.create(name: 'Electrum 30', brand: 'Marmot', weight: 2.7, size: 30, unit: "F", price: 160, image: 'http://www.ems.com/on/demandware.static/-/Sites-vestis-master-catalog/default/dw0133f1d6/product/images/1303/649/1303649/1303649_302_main.jpg')
Item.create(name: 'Furnace', brand: 'North Face', weight: 2.1, size: 35, unit: "F", price: 170, image: 'http://www.ems.com/on/demandware.static/-/Sites-vestis-master-catalog/default/dw52a4ebd7/product/images/1303/591/1303591/1303591_801_main.jpg')
Item.create(name: 'Superlight 35', brand: 'North Face', weight: 1.1, size: 35, unit: "F", price: 370, image: 'http://www.ems.com/on/demandware.static/-/Sites-vestis-master-catalog/default/dwc0e251b4/product/images/2016/241/2016241/2016241_004_main.jpg')
Item.create(name: 'Antares HD', brand: 'Thermarest', weight: 1.9, size: 27, unit: 'F', price: 350, image: 'http://www.trailexpeditions.com/media/thermarest-antares-hd-down-sleeping-bag.jpg')

Category.third.items.push(Item.find(21))
Category.third.items.push(Item.find(22))
Category.third.items.push(Item.find(23))
Category.third.items.push(Item.find(24))
Category.third.items.push(Item.find(25))
Category.third.items.push(Item.find(26))

Category.create(name: 'Bear Gear')
Item.create(name: 'Major Bear Bag', brand: 'Ursack', weight: 0.5, size: 925, unit: 'cu. in', price: 90, image: 'https://www.rei.com/media/b7f63c51-c6aa-4946-96f7-1ebda0c34459')
Item.create(name: 'BV500', brand: 'Bear Vault', weight: 2.6, size: 700, unit: 'cu. in', price: 80,image: 'https://www.rei.com/media/f04e4f7f-f82a-4b7d-987e-7a90ba158f2b')
Item.create(name: 'BV450', brand: 'Bear Vault', weight: 2.1, size: 440, unit: 'cu. in', price: 67,image: 'https://www.rei.com/media/f14fc199-86ba-46ae-ab10-34611ac9e52b?size=2000')
Item.create(name: 'Ultrasil Drysack', brand: 'Sea to Summit', weight: 0.1, size: 793, unit: 'cu. in', price: 22,image: 'https://www.rei.com/media/88c701de-0aed-447a-a353-10e053b30db4')
Category.fourth.items.push(Item.find(27))
Category.fourth.items.push(Item.find(28))
Category.fourth.items.push(Item.find(29))
Category.fourth.items.push(Item.find(30))

Category.create(name: 'Water Filtration')
Item.create(name: 'Aquamira', brand: 'Aquamira', weight: 0, size: 0, unit: 'N/A', price: 40, image: 'https://www.rei.com/media/664c143c-2d5e-45dc-b6fb-1edd30f38bbf')
Item.create(name: 'Sawyer Squeeze', brand: 'Sawyer', weight: 0.2, size: 0, unit: 'N/A', price: 70, image: 'https://www.rei.com/media/3d9c2dd5-3439-4edb-8807-8cd40b5ca7b5')
Item.create(name: 'Hiker Water Filter', brand: 'Katadyn', weight: 0.7, size: 0, unit: 'N/A', price: 15, image: 'https://www.rei.com/media/f4b0e169-77bd-4ef9-9b38-bc5e017e3c57')
Category.fifth.items.push(Item.find(31))
Category.fifth.items.push(Item.find(32))
Category.fifth.items.push(Item.find(33))

Category.create(name: 'Cookware')
Item.create(name: 'PocketRocket', brand: 'MSR', weight: 0.2 , size: 0 , unit: 'liters', price: 40, image: 'https://www.rei.com/media/a93f95c1-365c-4b82-ac67-cb96a25fb4ff')
Item.create(name: 'Jetboil Flash', brand: 'Jetboil', weight: 1, size: 2, unit: 'liters', price: 100, image: 'https://www.rei.com/media/86bf9207-aa8c-480d-bda0-f3ad7e1d0995')
Item.create(name: 'WindBurner', brand: 'MSR', weight: 1, size: 2, unit: 'liters', price: 130, image: 'https://www.rei.com/media/1f849c2e-3734-4078-a647-f1816f0132a2')
Category.find(6).items.push(Item.find(34))
Category.find(6).items.push(Item.find(35))
Category.find(6).items.push(Item.find(36))


List.create(name: 'Biking', image: 'https://www.facebook.com/photo.php?fbid=10207850059754316&set=pb.1380060301.-2207520000.1484725610.&type=3&theater')
# Item.create(name: '', brand: '', weight: , size: , unit: , price: , image: 'https://www.rei.com')

Category.create(name: 'Pannier')
Item.create(name: 'Back-Roller Classic', brand: 'Ortlieb', weight: 4.2, size: 40, unit: 'liters', price: 180, image: 'https://www.rei.com/media/092837f4-220c-477a-9166-b2dd23ee929f')
Item.create(name: 'Shild Panniers', brand: 'Thule', weight: 2.2, size: 48, unit: 'liters', price: 150, image: 'https://www.rei.com/media/e17149d1-b3b1-487f-a588-2ca3904d1133')
Item.create(name: 'Monsoon Aero', brand: 'Axiom', weight: 2.9, size: 24, unit: 'liters', price: 100, image: 'https://images-na.ssl-images-amazon.com/images/I/61eJITS6Q7L._SL1000_.jpg')
Item.create(name: 'Waterproof Pannier', brand: 'Banjo Brothers', weight: 2.2, size: 32, unit: 'liters', price: 50, image: 'https://images-na.ssl-images-amazon.com/images/I/81ouQt4TrlL._SX425_.jpg')
Item.create(name: 'Barrier', brand: 'Blackburn', weight: 2.3, size: 40, unit: 'liters', price: 110, image: 'https://www.blackburndesign.com/media/catalog/product/cache/1/small_image/352x/9df78eab33525d08d6e5fb8d27136e95/b/l/blackburn-barrier-city-waterproof-pannier.jpg')
Category.find(7).items.push(Item.find(37))
Category.find(7).items.push(Item.find(38))
Category.find(7).items.push(Item.find(39))
Category.find(7).items.push(Item.find(40))
Category.find(7).items.push(Item.find(41))

Category.create(name: 'Bike')
Item.create(name: 'Disc Trucker', brand: 'Surly', weight: 28, size: 0, unit: '', price: 1450, image: 'http://www.cyclingabout.com/wp-content/uploads/2011/12/2017-Surly-Disc-Trucker-Blue-Touring-Bike-1.jpg')
Item.create(name: 'AWOL', brand: 'Specialized', weight: 22.5, size: 0, unit: '', price: 1200, image: 'http://www.cyclingabout.com/wp-content/uploads/2016/08/2017-Specialized-AWOL-Expert-1000x597.jpeg')
Item.create(name: '520', brand: 'Trek', weight: 28, size: 0, unit: '', price: 1469, image: 'http://cyclingabout.com/wp-content/uploads/2015/10/Trek-920-Disc-2016.jpg')
Item.create(name: 'Sutra', brand: 'Kona', weight: 25.2, size: 0, unit: '', price: 1499, image: 'http://cyclingabout.com/wp-content/uploads/2015/10/Kona-Sutra-2016-Touring-01.jpg')
Item.create(name: 'Giramondo', brand: 'Masi', weight: 28, size: 0, unit: '', price: 1049, image: 'http://www.cyclingabout.com/wp-content/uploads/2015/04/Masi-Giramondo-Touring-Bike-2016.jpg')
Item.create(name: 'Marrakesh', brand: 'Salsa', weight: 32, size: 0, unit: '', price: 1599, image: 'http://www.cyclingabout.com/wp-content/uploads/2015/07/Salsa-Marrakesh-Drop-Green.jpg')
Item.create(name: 'Tour de Fer', brand: 'Genesis', weight: 33, size: 0, unit: '', price: 1200, image: 'http://cyclingabout.com/wp-content/uploads/2015/10/2016-Genesis-Tour-de-Fer-20-1.jpg')
Item.create(name: 'Touring', brand: 'Fuji', weight: 26.3, size: 0, unit: '', price: 749, image: 'http://cyclingabout.com/wp-content/uploads/2015/10/Fuji-Touring-2016-1.jpg')
Category.find(8).items.push(Item.find(42))
Category.find(8).items.push(Item.find(43))
Category.find(8).items.push(Item.find(44))
Category.find(8).items.push(Item.find(45))
Category.find(8).items.push(Item.find(46))
Category.find(8).items.push(Item.find(47))
Category.find(8).items.push(Item.find(48))
Category.find(8).items.push(Item.find(49))

List.create(name: 'Canoeing', image: 'https://scontent-yyz1-1.xx.fbcdn.net/v/t1.0-9/14212796_10207786536606277_5502408418187962023_n.jpg?oh=aecfa1bf69260984ac84debd7362c9a0&oe=58C600E9')

Category.create(name: 'Canoe')
List.first.categories.push(Category.first)
List.first.categories.push(Category.find(2))
List.first.categories.push(Category.find(3))
List.first.categories.push(Category.find(4))
List.first.categories.push(Category.find(5))
List.first.categories.push(Category.find(6))


List.second.categories.push(Category.find(2))
List.second.categories.push(Category.find(3))
List.second.categories.push(Category.find(6))
List.second.categories.push(Category.find(7))
List.second.categories.push(Category.find(8))
List.last.categories.push(Category.find(2))
List.last.categories.push(Category.find(3))
List.last.categories.push(Category.find(5))
List.last.categories.push(Category.find(6))

# ChecklistItem.create(name: '', checked: false, advice: '', checklist_id:)
Checklist.create(name: 'hiking list')
ChecklistItem.create(important: true, name: 'poles', checked: false, advice: 'Essential to save your knees', checklist_id: 1)
ChecklistItem.create(important: true, name: 'sleeping pad', checked: false, advice: 'You could sleep on the ground, but this is more pleasant', checklist_id: 1)
ChecklistItem.create(important: true, name: 'Headlamp', checked: false, advice: 'Keep it light and cheap', checklist_id: 1)
ChecklistItem.create(important: true, name: 'Water Bladder', checked: false, advice: 'User Platypus brand, very reliable and affordable', checklist_id: 1)
ChecklistItem.create(important: true, name: 'Silverware', checked: false, advice: 'Cheap, light metal is ideal', checklist_id: 1)
ChecklistItem.create(important: true, name: 'Iodine', checked: false, advice: "It's important to have a back up purification system, just in case", checklist_id: 1)
ChecklistItem.create(important: true, name: 'Knife', checked: false, advice: 'Good to have around camp', checklist_id: 1)
ChecklistItem.create(important: true, name: 'First Aid Kit', checked: false, advice: 'REI sells weekend trip kits that are perfect for all your backpacking needs', checklist_id: 1)
ChecklistItem.create(important: true, name: '2 pairs of socks', checked: false, advice: "You need two, otherwise they'll never get dry and you'll get trach foot", checklist_id: 1)
ChecklistItem.create(important: true, name: 'Rain Pants', checked: false, advice: "It keeps you dry and can still be worn as pants when it's not raining", checklist_id: 1)
ChecklistItem.create(important: true, name: 'Shorts', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: true, name: 'Shirt', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: true, name: 'Puffy Jacket', checked: false, advice: 'Perfect to keep you warm in most conditions you will encounter', checklist_id: 1)
ChecklistItem.create(important: true, name: 'Rain Coat', checked: false, advice: 'It will rain, or even snow, and getting wet and cold can be very dangerous', checklist_id: 1)
ChecklistItem.create(important: false, name: 'Hat', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: false, name: 'rope', checked: false, advice: 'Good for bear lines', checklist_id: 1)
ChecklistItem.create(important: false, name: 'Bug Spray', checked: false, advice: 'You need it in Maine', checklist_id: 1)
ChecklistItem.create(important: false, name: 'Toothbrush', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: false, name: 'Toothpaste', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: false, name: 'Ear Plugs', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: false, name: 'Compressions Dry Sacks', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: false, name: 'Sunblock', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: false, name: 'External Charger', checked: false, advice: '', checklist_id: 1)
ChecklistItem.create(important: false, name: 'Sleeping Bag Liner', checked: false, advice: '', checklist_id: 1)

Checklist.create(name: 'biking list')
ChecklistItem.create(important: true, name: 'Helmet', checked: false, advice: 'A Must for Any Long Bike Trip', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Saddlebag Bag', checked: false, advice: 'Extra storgae in on the handlebars', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Handlebar Bag', checked: false, advice: 'Extra storgae in an underseat bag', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Cargo Rack', checked: false, advice: 'For back tire to carry panniers', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Bike Lights', checked: false, advice: 'Can also be used to light up camp', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Lock', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: true, name: 'GPS', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Mirror', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Watterbottles', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Pump', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Tire Levers', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Multitool', checked: false, advice: 'With an integrated allen wrench', checklist_id: 2)
ChecklistItem.create(important: false, name: 'Oil', checked: false, advice: 'Keeps the bike running smoothly', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Spare Tire', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: false, name: 'Rainwear', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: false, name: 'Wicking Jersey', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: false, name: 'Biking Shoes', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Windbreaker', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: false, name: 'Sunscreen', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: false, name: 'External Battery Back', checked: false, advice: '', checklist_id: 2)
ChecklistItem.create(important: false, name: 'First Aid Kit', checked: false, advice: 'Can be found in most outdoor sports stores', checklist_id: 2)
ChecklistItem.create(important: true, name: 'Fender', checked: false, advice: 'Great to keep yourself a little dryer on the wet roads', checklist_id: 2)


Checklist.create(name: 'canoeing list')

User.all.each do |u|
  ChecklistItem.all.each do |check|
    UserChecklistItem.create(checked: false, user_id: u.id, checklist_item_id: check.id)
  end
end
